server:
  port: 8089

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: Nitin@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

razorpay:
  key-id: rzp_test_SiqdWDaaK8yVa2
  key-secret: kMssYLhLWf3A0fUbmTlaBUGr

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
